[package]
authors = ["Saverio Miroddi <saverio.pub2@gmail.com>"]
edition = "2018"
name = "frontend-sdl"
version = "0.1.0"

[dependencies]
interfaces-frontend = {path = "../interfaces-frontend"}
sdl2 = "0.34.2"
