[package]
authors = ["Saverio Miroddi <saverio.pub2@gmail.com>"]
edition = "2018"
name = "playground"
version = "0.1.0"

[workspace]

[dependencies]
bus = "2.2.3"
clap = "2.33.3"
futures = "0.3.5"
rand = "0.7.3"
sdl2 = "0.34.3"
